# Generated by Django 4.1.5 on 2023-01-05 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('order', models.IntegerField(default=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='calculator.game')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('cost', models.IntegerField()),
                ('divident', models.IntegerField()),
                ('value_up', models.IntegerField()),
                ('value_down', models.IntegerField()),
                ('profit_3up', models.IntegerField()),
                ('profit_2up', models.IntegerField()),
                ('profit_1up', models.IntegerField()),
                ('profit_0', models.IntegerField()),
                ('profit_1down', models.IntegerField()),
                ('profit_2down', models.IntegerField()),
                ('profit_3down', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='calculator.game')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='calculator.player')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='calculator.share')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='calculator.turn')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_forecast', models.IntegerField(default=0)),
                ('main_forecast', models.IntegerField(default=0)),
                ('secondary_forecast', models.IntegerField(default=0)),
                ('all_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast0', to='calculator.share')),
                ('main_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast1', to='calculator.share')),
                ('secondary_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast2', to='calculator.share')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='calculator.turn')),
            ],
        ),
    ]
