# Generated by Django 4.1.5 on 2023-01-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20230105_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='all_company',
        ),
    ]
