# Generated by Django 4.1.5 on 2023-01-09 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_remove_forecast_all_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='main_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast1', to='calculator.share'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='secondary_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast2', to='calculator.share'),
        ),
    ]
